#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_biblioteca")]
public partial class ConexionLQDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertAnime(Anime instance);
  partial void UpdateAnime(Anime instance);
  partial void DeleteAnime(Anime instance);
  partial void InsertUsuario(Usuario instance);
  partial void UpdateUsuario(Usuario instance);
  partial void DeleteUsuario(Usuario instance);
  partial void InsertEstado_Serie(Estado_Serie instance);
  partial void UpdateEstado_Serie(Estado_Serie instance);
  partial void DeleteEstado_Serie(Estado_Serie instance);
  partial void InsertGenero_Anime(Genero_Anime instance);
  partial void UpdateGenero_Anime(Genero_Anime instance);
  partial void DeleteGenero_Anime(Genero_Anime instance);
  #endregion
	
	public ConexionLQDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bd_bibliotecaConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ConexionLQDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ConexionLQDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ConexionLQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ConexionLQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Anime> Anime
	{
		get
		{
			return this.GetTable<Anime>();
		}
	}
	
	public System.Data.Linq.Table<Usuario> Usuario
	{
		get
		{
			return this.GetTable<Usuario>();
		}
	}
	
	public System.Data.Linq.Table<vAnime> vAnime
	{
		get
		{
			return this.GetTable<vAnime>();
		}
	}
	
	public System.Data.Linq.Table<Estado_Serie> Estado_Serie
	{
		get
		{
			return this.GetTable<Estado_Serie>();
		}
	}
	
	public System.Data.Linq.Table<Genero_Anime> Genero_Anime
	{
		get
		{
			return this.GetTable<Genero_Anime>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vAnimeUsuario")]
	public ISingleResult<vAnimeUsuarioResult> vAnimeUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User", DbType="VarChar(50)")] string user)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
		return ((ISingleResult<vAnimeUsuarioResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vDetalleAnime")]
	public ISingleResult<vDetalleAnimeResult> vDetalleAnime([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User", DbType="VarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Anime", DbType="Int")] System.Nullable<int> anime)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, anime);
		return ((ISingleResult<vDetalleAnimeResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Anime")]
public partial class Anime : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Anime;
	
	private string _Nombre;
	
	private string _Sinopsis;
	
	private System.DateTime _Lanzamiento;
	
	private int _Temporadas;
	
	private int _CapitulosTotales;
	
	private string _Imagen;
	
	private System.Nullable<int> _id_GeneroAnime;
	
	private string _Otros_Generos;
	
	private int _id_EstadoSerie;
	
	private EntityRef<Estado_Serie> _Estado_Serie;
	
	private EntityRef<Genero_Anime> _Genero_Anime;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_AnimeChanging(int value);
    partial void Onid_AnimeChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnSinopsisChanging(string value);
    partial void OnSinopsisChanged();
    partial void OnLanzamientoChanging(System.DateTime value);
    partial void OnLanzamientoChanged();
    partial void OnTemporadasChanging(int value);
    partial void OnTemporadasChanged();
    partial void OnCapitulosTotalesChanging(int value);
    partial void OnCapitulosTotalesChanged();
    partial void OnImagenChanging(string value);
    partial void OnImagenChanged();
    partial void Onid_GeneroAnimeChanging(System.Nullable<int> value);
    partial void Onid_GeneroAnimeChanged();
    partial void OnOtros_GenerosChanging(string value);
    partial void OnOtros_GenerosChanged();
    partial void Onid_EstadoSerieChanging(int value);
    partial void Onid_EstadoSerieChanged();
    #endregion
	
	public Anime()
	{
		this._Estado_Serie = default(EntityRef<Estado_Serie>);
		this._Genero_Anime = default(EntityRef<Genero_Anime>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Anime", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Anime
	{
		get
		{
			return this._id_Anime;
		}
		set
		{
			if ((this._id_Anime != value))
			{
				this.Onid_AnimeChanging(value);
				this.SendPropertyChanging();
				this._id_Anime = value;
				this.SendPropertyChanged("id_Anime");
				this.Onid_AnimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sinopsis", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Sinopsis
	{
		get
		{
			return this._Sinopsis;
		}
		set
		{
			if ((this._Sinopsis != value))
			{
				this.OnSinopsisChanging(value);
				this.SendPropertyChanging();
				this._Sinopsis = value;
				this.SendPropertyChanged("Sinopsis");
				this.OnSinopsisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanzamiento", DbType="Date NOT NULL")]
	public System.DateTime Lanzamiento
	{
		get
		{
			return this._Lanzamiento;
		}
		set
		{
			if ((this._Lanzamiento != value))
			{
				this.OnLanzamientoChanging(value);
				this.SendPropertyChanging();
				this._Lanzamiento = value;
				this.SendPropertyChanged("Lanzamiento");
				this.OnLanzamientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temporadas", DbType="Int NOT NULL")]
	public int Temporadas
	{
		get
		{
			return this._Temporadas;
		}
		set
		{
			if ((this._Temporadas != value))
			{
				this.OnTemporadasChanging(value);
				this.SendPropertyChanging();
				this._Temporadas = value;
				this.SendPropertyChanged("Temporadas");
				this.OnTemporadasChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapitulosTotales", DbType="Int NOT NULL")]
	public int CapitulosTotales
	{
		get
		{
			return this._CapitulosTotales;
		}
		set
		{
			if ((this._CapitulosTotales != value))
			{
				this.OnCapitulosTotalesChanging(value);
				this.SendPropertyChanging();
				this._CapitulosTotales = value;
				this.SendPropertyChanged("CapitulosTotales");
				this.OnCapitulosTotalesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(MAX)")]
	public string Imagen
	{
		get
		{
			return this._Imagen;
		}
		set
		{
			if ((this._Imagen != value))
			{
				this.OnImagenChanging(value);
				this.SendPropertyChanging();
				this._Imagen = value;
				this.SendPropertyChanged("Imagen");
				this.OnImagenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_GeneroAnime", DbType="Int")]
	public System.Nullable<int> id_GeneroAnime
	{
		get
		{
			return this._id_GeneroAnime;
		}
		set
		{
			if ((this._id_GeneroAnime != value))
			{
				if (this._Genero_Anime.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_GeneroAnimeChanging(value);
				this.SendPropertyChanging();
				this._id_GeneroAnime = value;
				this.SendPropertyChanged("id_GeneroAnime");
				this.Onid_GeneroAnimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Otros_Generos", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Otros_Generos
	{
		get
		{
			return this._Otros_Generos;
		}
		set
		{
			if ((this._Otros_Generos != value))
			{
				this.OnOtros_GenerosChanging(value);
				this.SendPropertyChanging();
				this._Otros_Generos = value;
				this.SendPropertyChanged("Otros_Generos");
				this.OnOtros_GenerosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_EstadoSerie", DbType="Int NOT NULL")]
	public int id_EstadoSerie
	{
		get
		{
			return this._id_EstadoSerie;
		}
		set
		{
			if ((this._id_EstadoSerie != value))
			{
				if (this._Estado_Serie.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_EstadoSerieChanging(value);
				this.SendPropertyChanging();
				this._id_EstadoSerie = value;
				this.SendPropertyChanged("id_EstadoSerie");
				this.Onid_EstadoSerieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Serie_Anime", Storage="_Estado_Serie", ThisKey="id_EstadoSerie", OtherKey="id_EstadoSerie", IsForeignKey=true)]
	public Estado_Serie Estado_Serie
	{
		get
		{
			return this._Estado_Serie.Entity;
		}
		set
		{
			Estado_Serie previousValue = this._Estado_Serie.Entity;
			if (((previousValue != value) 
						|| (this._Estado_Serie.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Estado_Serie.Entity = null;
					previousValue.Anime.Remove(this);
				}
				this._Estado_Serie.Entity = value;
				if ((value != null))
				{
					value.Anime.Add(this);
					this._id_EstadoSerie = value.id_EstadoSerie;
				}
				else
				{
					this._id_EstadoSerie = default(int);
				}
				this.SendPropertyChanged("Estado_Serie");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Genero_Anime_Anime", Storage="_Genero_Anime", ThisKey="id_GeneroAnime", OtherKey="id_GeneroAnime", IsForeignKey=true)]
	public Genero_Anime Genero_Anime
	{
		get
		{
			return this._Genero_Anime.Entity;
		}
		set
		{
			Genero_Anime previousValue = this._Genero_Anime.Entity;
			if (((previousValue != value) 
						|| (this._Genero_Anime.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Genero_Anime.Entity = null;
					previousValue.Anime.Remove(this);
				}
				this._Genero_Anime.Entity = value;
				if ((value != null))
				{
					value.Anime.Add(this);
					this._id_GeneroAnime = value.id_GeneroAnime;
				}
				else
				{
					this._id_GeneroAnime = default(Nullable<int>);
				}
				this.SendPropertyChanged("Genero_Anime");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Usuario;
	
	private string _Nick;
	
	private string _Password;
	
	private System.Nullable<int> _id_EstadoUsuario;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_UsuarioChanging(int value);
    partial void Onid_UsuarioChanged();
    partial void OnNickChanging(string value);
    partial void OnNickChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void Onid_EstadoUsuarioChanging(System.Nullable<int> value);
    partial void Onid_EstadoUsuarioChanged();
    #endregion
	
	public Usuario()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id_Usuario
	{
		get
		{
			return this._id_Usuario;
		}
		set
		{
			if ((this._id_Usuario != value))
			{
				this.Onid_UsuarioChanging(value);
				this.SendPropertyChanging();
				this._id_Usuario = value;
				this.SendPropertyChanged("id_Usuario");
				this.Onid_UsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nick", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Nick
	{
		get
		{
			return this._Nick;
		}
		set
		{
			if ((this._Nick != value))
			{
				this.OnNickChanging(value);
				this.SendPropertyChanging();
				this._Nick = value;
				this.SendPropertyChanged("Nick");
				this.OnNickChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_EstadoUsuario", DbType="Int")]
	public System.Nullable<int> id_EstadoUsuario
	{
		get
		{
			return this._id_EstadoUsuario;
		}
		set
		{
			if ((this._id_EstadoUsuario != value))
			{
				this.Onid_EstadoUsuarioChanging(value);
				this.SendPropertyChanging();
				this._id_EstadoUsuario = value;
				this.SendPropertyChanged("id_EstadoUsuario");
				this.Onid_EstadoUsuarioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAnime")]
public partial class vAnime
{
	
	private int _id_Anime;
	
	private string _Nombre;
	
	private string _Sinopsis;
	
	private string _Lanzamiento;
	
	private int _Temporadas;
	
	private int _Capitulos;
	
	private string _Imagen;
	
	private string _Genero;
	
	private string _Otros_Generos;
	
	private string _Estado;
	
	public vAnime()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Anime", DbType="Int NOT NULL")]
	public int id_Anime
	{
		get
		{
			return this._id_Anime;
		}
		set
		{
			if ((this._id_Anime != value))
			{
				this._id_Anime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sinopsis", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Sinopsis
	{
		get
		{
			return this._Sinopsis;
		}
		set
		{
			if ((this._Sinopsis != value))
			{
				this._Sinopsis = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanzamiento", DbType="VarChar(30)")]
	public string Lanzamiento
	{
		get
		{
			return this._Lanzamiento;
		}
		set
		{
			if ((this._Lanzamiento != value))
			{
				this._Lanzamiento = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temporadas", DbType="Int NOT NULL")]
	public int Temporadas
	{
		get
		{
			return this._Temporadas;
		}
		set
		{
			if ((this._Temporadas != value))
			{
				this._Temporadas = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capitulos", DbType="Int NOT NULL")]
	public int Capitulos
	{
		get
		{
			return this._Capitulos;
		}
		set
		{
			if ((this._Capitulos != value))
			{
				this._Capitulos = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(MAX)")]
	public string Imagen
	{
		get
		{
			return this._Imagen;
		}
		set
		{
			if ((this._Imagen != value))
			{
				this._Imagen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Genero
	{
		get
		{
			return this._Genero;
		}
		set
		{
			if ((this._Genero != value))
			{
				this._Genero = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Otros Generos]", Storage="_Otros_Generos", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Otros_Generos
	{
		get
		{
			return this._Otros_Generos;
		}
		set
		{
			if ((this._Otros_Generos != value))
			{
				this._Otros_Generos = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado_Serie")]
public partial class Estado_Serie : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_EstadoSerie;
	
	private string _Descripcion;
	
	private EntitySet<Anime> _Anime;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_EstadoSerieChanging(int value);
    partial void Onid_EstadoSerieChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
	
	public Estado_Serie()
	{
		this._Anime = new EntitySet<Anime>(new Action<Anime>(this.attach_Anime), new Action<Anime>(this.detach_Anime));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_EstadoSerie", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id_EstadoSerie
	{
		get
		{
			return this._id_EstadoSerie;
		}
		set
		{
			if ((this._id_EstadoSerie != value))
			{
				this.Onid_EstadoSerieChanging(value);
				this.SendPropertyChanging();
				this._id_EstadoSerie = value;
				this.SendPropertyChanged("id_EstadoSerie");
				this.Onid_EstadoSerieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Descripcion
	{
		get
		{
			return this._Descripcion;
		}
		set
		{
			if ((this._Descripcion != value))
			{
				this.OnDescripcionChanging(value);
				this.SendPropertyChanging();
				this._Descripcion = value;
				this.SendPropertyChanged("Descripcion");
				this.OnDescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Serie_Anime", Storage="_Anime", ThisKey="id_EstadoSerie", OtherKey="id_EstadoSerie")]
	public EntitySet<Anime> Anime
	{
		get
		{
			return this._Anime;
		}
		set
		{
			this._Anime.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Anime(Anime entity)
	{
		this.SendPropertyChanging();
		entity.Estado_Serie = this;
	}
	
	private void detach_Anime(Anime entity)
	{
		this.SendPropertyChanging();
		entity.Estado_Serie = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Genero_Anime")]
public partial class Genero_Anime : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_GeneroAnime;
	
	private string _Descripcion;
	
	private EntitySet<Anime> _Anime;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_GeneroAnimeChanging(int value);
    partial void Onid_GeneroAnimeChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
	
	public Genero_Anime()
	{
		this._Anime = new EntitySet<Anime>(new Action<Anime>(this.attach_Anime), new Action<Anime>(this.detach_Anime));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_GeneroAnime", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_GeneroAnime
	{
		get
		{
			return this._id_GeneroAnime;
		}
		set
		{
			if ((this._id_GeneroAnime != value))
			{
				this.Onid_GeneroAnimeChanging(value);
				this.SendPropertyChanging();
				this._id_GeneroAnime = value;
				this.SendPropertyChanged("id_GeneroAnime");
				this.Onid_GeneroAnimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Descripcion
	{
		get
		{
			return this._Descripcion;
		}
		set
		{
			if ((this._Descripcion != value))
			{
				this.OnDescripcionChanging(value);
				this.SendPropertyChanging();
				this._Descripcion = value;
				this.SendPropertyChanged("Descripcion");
				this.OnDescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Genero_Anime_Anime", Storage="_Anime", ThisKey="id_GeneroAnime", OtherKey="id_GeneroAnime")]
	public EntitySet<Anime> Anime
	{
		get
		{
			return this._Anime;
		}
		set
		{
			this._Anime.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Anime(Anime entity)
	{
		this.SendPropertyChanging();
		entity.Genero_Anime = this;
	}
	
	private void detach_Anime(Anime entity)
	{
		this.SendPropertyChanging();
		entity.Genero_Anime = null;
	}
}

public partial class vAnimeUsuarioResult
{
	
	private int _id_Anime;
	
	private string _Nombre;
	
	private string _Sinopsis;
	
	private string _Lanzamiento;
	
	private int _Temporadas;
	
	private int _Capitulos;
	
	private string _Imagen;
	
	private string _Genero;
	
	private string _Estado;
	
	public vAnimeUsuarioResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Anime", DbType="Int NOT NULL")]
	public int id_Anime
	{
		get
		{
			return this._id_Anime;
		}
		set
		{
			if ((this._id_Anime != value))
			{
				this._id_Anime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sinopsis", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Sinopsis
	{
		get
		{
			return this._Sinopsis;
		}
		set
		{
			if ((this._Sinopsis != value))
			{
				this._Sinopsis = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanzamiento", DbType="VarChar(30)")]
	public string Lanzamiento
	{
		get
		{
			return this._Lanzamiento;
		}
		set
		{
			if ((this._Lanzamiento != value))
			{
				this._Lanzamiento = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temporadas", DbType="Int NOT NULL")]
	public int Temporadas
	{
		get
		{
			return this._Temporadas;
		}
		set
		{
			if ((this._Temporadas != value))
			{
				this._Temporadas = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capitulos", DbType="Int NOT NULL")]
	public int Capitulos
	{
		get
		{
			return this._Capitulos;
		}
		set
		{
			if ((this._Capitulos != value))
			{
				this._Capitulos = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(MAX)")]
	public string Imagen
	{
		get
		{
			return this._Imagen;
		}
		set
		{
			if ((this._Imagen != value))
			{
				this._Imagen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Genero
	{
		get
		{
			return this._Genero;
		}
		set
		{
			if ((this._Genero != value))
			{
				this._Genero = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
}

public partial class vDetalleAnimeResult
{
	
	private int _id_Anime;
	
	private string _Nombre;
	
	private string _Sinopsis;
	
	private string _Lanzamiento;
	
	private int _Temporadas;
	
	private int _Capitulos;
	
	private string _Imagen;
	
	private string _Genero;
	
	private string _Otros_Generos;
	
	private string _Estado;
	
	private string _Avance;
	
	public vDetalleAnimeResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Anime", DbType="Int NOT NULL")]
	public int id_Anime
	{
		get
		{
			return this._id_Anime;
		}
		set
		{
			if ((this._id_Anime != value))
			{
				this._id_Anime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sinopsis", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Sinopsis
	{
		get
		{
			return this._Sinopsis;
		}
		set
		{
			if ((this._Sinopsis != value))
			{
				this._Sinopsis = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanzamiento", DbType="VarChar(30)")]
	public string Lanzamiento
	{
		get
		{
			return this._Lanzamiento;
		}
		set
		{
			if ((this._Lanzamiento != value))
			{
				this._Lanzamiento = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temporadas", DbType="Int NOT NULL")]
	public int Temporadas
	{
		get
		{
			return this._Temporadas;
		}
		set
		{
			if ((this._Temporadas != value))
			{
				this._Temporadas = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capitulos", DbType="Int NOT NULL")]
	public int Capitulos
	{
		get
		{
			return this._Capitulos;
		}
		set
		{
			if ((this._Capitulos != value))
			{
				this._Capitulos = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(MAX)")]
	public string Imagen
	{
		get
		{
			return this._Imagen;
		}
		set
		{
			if ((this._Imagen != value))
			{
				this._Imagen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Genero
	{
		get
		{
			return this._Genero;
		}
		set
		{
			if ((this._Genero != value))
			{
				this._Genero = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Otros Generos]", Storage="_Otros_Generos", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Otros_Generos
	{
		get
		{
			return this._Otros_Generos;
		}
		set
		{
			if ((this._Otros_Generos != value))
			{
				this._Otros_Generos = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avance", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Avance
	{
		get
		{
			return this._Avance;
		}
		set
		{
			if ((this._Avance != value))
			{
				this._Avance = value;
			}
		}
	}
}
#pragma warning restore 1591
